/*
 * DECLARE CONSTANTS HERE
 */

#ifndef SRC_ROBOTPARAMETERS_H_
#define SRC_ROBOTPARAMETERS_H_

#define DRIVE_SPEED_CONTROLLER_FL_CHANNEL 2
#define DRIVE_SPEED_CONTROLLER_FR_CHANNEL 0
#define DRIVE_SPEED_CONTROLLER_BL_CHANNEL 3
#define DRIVE_SPEED_CONTROLLER_BR_CHANNEL 1
#define DRIVE_SPEED_CONTROLLER_LIFT_1_CHANNEL 	4
#define DRIVE_SPEED_CONTROLLER_LIFT_2_CHANNEL 	5
#define GYRO_SPI_PORT 							SPI::kOnboardCS0

#define RIGHT_TRIGGER 3
#define LEFT_TRIGGER 2

#endif /* SRC_ROBOTPARAMETERS_H_ */
